#Problem 26, Reciprocal Cycles
import time 
t = time.time()
def carmichael(x):
	m = 1
	val = 10**m
	while val%x != 1:
		m += 1
		val = 10**m 


	return m



largest_i = 0
largest = 0
for i in range(2,1001):
	if (i%2 == 0) | (i%5 == 0):
		#messes with the cyclic group generated by 10 
		continue
	else:
		print i
		temp = carmichael(i)
		if temp > largest:
			largest = temp
			largest_i = i


print largest, largest_i
